# Site
name: "Veronica Vaca"
title: "Veronica Vaca"
description: "ultralearner"
meta_description: "Jekyll theme for blogging."
logo: 'assets/images/vero_small_logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'veronica.vaca@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  veronicavaca:
    name: Veronica Vaca
    display_name: Veronica Vaca
    gravatar: 525186e528d66577cec19fd74079f350
    email: veronica.vaca@gmail.com
    web: https://www.veronicavaca.com/
    twitter: https://twitter.com/VeronicaVacaB
    description: ""

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
